version: "2"

linters:
  default: none
  enable:
    - bodyclose
    # - depguard # TODO: Re-enable later
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    # - lll # TODO: Re-enable later
    - misspell
    # - mnd # TODO: Re-enable later
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - paramTypeCombine # I'm not sure it makes code more readable
        - hugeParam # TODO: Re-consider this later
    staticcheck:
      checks:
        - all
        - "-ST1003" # TODO: Deal with variable names later
        - "-ST1005" # TODO: Re-think error messages policy later
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
    rules:
      - path: "(.+)_test\\.go"
        linters:
          - goconst
          - mnd

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
