version: 2
project_name: pct

release:
  prerelease: auto

before:
  hooks:
    - go mod tidy
    - go fmt ./...

builds:
  - id: pct
    binary: pct
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.CommitDate}}
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - ids:
      - pct
    wrap_in_directory: false
    format_overrides:
      - goos: windows
        formats: ["zip"]
    files:
      - templates/**/*

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ .Tag }}-{{.ShortCommit}}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
