name: Installation Tests

on:
  pull_request:
    branches: [ main ]
    # Only execute this workflow if anything related changed
    paths:
      - scripts/install.*
      - .goreleaser.yml

permissions:
  contents: read

jobs:
  install_test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      PCT_INSTALL_DEBUG: true
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        fetch-depth: 0
        persist-credentials: false
    - name: Install PCT (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        .\scripts\install.ps1
    - name: Validate install (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        & "$env:USERPROFILE\.puppetlabs\pct\pct.exe" --version |
          Select-String "pct $((git tag --list |
            Where-Object { $_ -match '^v\d+\.\d+\.\d+$' } |
            Sort-Object -Descending | Select-Object -First 1).TrimStart('v'))"
    - name: Install PCT (Unix)
      if: runner.os != 'Windows'
      run: ./scripts/install.sh
    - name: Validate install (Unix)
      if: runner.os != 'Windows'
      run: $HOME/.puppetlabs/pct/pct --version | grep "pct $(git tag | awk -F'v' 'END{print $2}')"
