name: Test

on:
  pull_request:
    branches: [ main ]

env:
  go_version: 1.24

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v6
      with:
        submodules: true

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: ${{ env.go_version }}

    - name: Build single target
      uses: goreleaser/goreleaser-action@v7
      with:
        args: build --clean --snapshot --single-target -o pct.exe

    - name: Run unit tests
      run: go test -v ./...

    - name: Run acceptance tests
      run: go test -v ./acceptance/...
      env:
        # A template deployment code uses `rename()` to move a template to the
        # destination directory. That fails when temporary path is on different
        # filesystem/disk. Windows runners has TMP on another disk by default.
        # Set TMP explicitly to workaround it for now.
        TMP: ${{ github.workspace }}/tmp
        TEST_ACCEPTANCE: true
